FROM python:3.10-slim

WORKDIR /app

# Копируем файлы зависимостей
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt streamlit

# Копируем только необходимые файлы для UI
COPY ui /app/ui

# Запускаем Streamlit-приложение
CMD ["streamlit", "run", "ui/app.py", "--server.port=8501", "--server.address=0.0.0.0"]

# Открываем порт
EXPOSE 8501